# 网关端口号
server:
  port: 80
spring:
# 去掉web模块
  main:
    web-application-type: reactive
# 网关服务名称
  application:
    name: service-gateway
  cloud:
# nacos 注册中心 服务地址
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
# 网关设置
      routes[0]:
# 注册service-hosp服务路由
# 路由id
        id: service-dict
#设置路由的uri
        uri: lb://service-dict
#设置路由断言,代理servicerId为auth-service的/auth/路径
        predicates: Path=/*/dict/**
      routes[1]:
# 注册service-hosp服务路由
# 路由id
        id: service-hospital
#设置路由的uri
        uri: lb://service-hospital
#设置路由断言,代理serviceId为auth-service的/auth/路径
        predicates: Path=/*/hosp/**
      routes[2]:
        # 注册service-hosp服务路由
        # 路由id
        id: service-car
        #设置路由的uri
        uri: lb://service-car
        #设置路由断言,代理serviceId为auth-service的/auth/路径
        predicates: Path=/*/car/**
      routes[3]:
        id: service-user
        uri: lb://service-user
        predicates: Path=/*/user/**
      routes[4]:
        id: service-msm
        uri: lb://service-msm
        predicates: Path=/*/msm/**